baseURL = "https://roshnimohandas.com/"
languageCode = "en-us"
title = "Roshni Mohandas | Machine Learning, Artificial intelligence"
theme = "prabhat-simple"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "Gallery"
        url     = "/gallery"
        weight  = 2
    [[menu.nav]]
        name    = "Blog"
        url     = "/blog"
        weight  = 3

# Site Params
[params]
    home = "Home"
    logo = "images/about/roshni_name1.png"
    dateFormat = "6 January 2006"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider3.jpg"
        heading = "Hello, I am \"Roshni Mohandas\". I am a"
        description = "I am a ML practictioner"
        [[params.banner.flipText]]
            title   = "Builder"
        [[params.banner.flipText]]
            title   = "Daughter"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "About Me"
        content = "A machine learning enthusiast with experience of close to 12 years having worked with clients across domains including technology , financial services, retail and manufacturing. <br><br>In previous assignment, have also handled training sessions in Deep learning & Machine learning for individuals and some of the corporates in India. <br><br> A Mathematics major and MBA from Symbiosis Pune in Marketing. Also completed a formal training from Indian Institute of Management in Business Analytics and Intelligence"
        image   = "images/about/me.jpg"

    