name = "Roshni Home"
tags = ['hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'company', 'projects', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'pages']
features = ['bootstrap','responsive']
min_version = "0.1"

[author]
  name = "Roshni Mohandas"
  homepage = "https://roshnimohandas.in/"